# Generated by Django 5.0 on 2023-12-24 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_file_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_file',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pptx', 'xlsx', 'docx'])]),
        ),
    ]
